/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.65
 * Generated at: 2023-12-09 20:01:55 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class add_002dproduct_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\" />\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\" />\r\n");
      out.write("<title>Add Product - Dashboard HTML Template</title>\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://fonts.googleapis.com/css?family=Roboto:400,700\" />\r\n");
      out.write("<!-- https://fonts.google.com/specimen/Roboto -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/fontawesome.min.css\" />\r\n");
      out.write("<!-- https://fontawesome.com/ -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"jquery-ui-datepicker/jquery-ui.min.css\"\r\n");
      out.write("	type=\"text/css\" />\r\n");
      out.write("<!-- http://api.jqueryui.com/datepicker/ -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/bootstrap.min.css\" />\r\n");
      out.write("<!-- https://getbootstrap.com/ -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/templatemo-style.css\">  \r\n");
      out.write("\r\n");
      out.write("<!--\r\n");
      out.write("	Product Admin CSS Template\r\n");
      out.write("	https://templatemo.com/tm-524-product-admin\r\n");
      out.write("	-->\r\n");
      out.write("	<style>   \r\n");
      out.write("	\r\n");
      out.write("	   .row {\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    display: -ms-flexbox;\r\n");
      out.write("    display: flex;\r\n");
      out.write("    -ms-flex-wrap: wrap;\r\n");
      out.write("    flex-wrap: wrap;\r\n");
      out.write("    margin-right: -15px;\r\n");
      out.write("    margin-left: -15px;\r\n");
      out.write("  }\r\n");
      out.write("       .tm-block-title {\r\n");
      out.write("    margin-bottom: 0;\r\n");
      out.write("    \r\n");
      out.write("   }\r\n");
      out.write("        .red {\r\n");
      out.write("	color: red;\r\n");
      out.write("    }\r\n");
      out.write("	</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("     ");

		String baoLoi = request.getAttribute("baoLoi")+"";
		baoLoi = (baoLoi.equals("null"))?"":baoLoi;
	
	
      out.write("\r\n");
      out.write("	<nav class=\"navbar navbar-expand-xl\">\r\n");
      out.write("		<div class=\"container h-100\">\r\n");
      out.write("			<a class=\"navbar-brand\" href=\"index.html\">\r\n");
      out.write("				<h1 class=\"tm-site-title mb-0\">Product Admin</h1>\r\n");
      out.write("			</a>\r\n");
      out.write("			<button class=\"navbar-toggler ml-auto mr-0\" type=\"button\"\r\n");
      out.write("				data-toggle=\"collapse\" data-target=\"#navbarSupportedContent\"\r\n");
      out.write("				aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\"\r\n");
      out.write("				aria-label=\"Toggle navigation\">\r\n");
      out.write("				<i class=\"fas fa-bars tm-nav-icon\"></i>\r\n");
      out.write("			</button>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\r\n");
      out.write("				<ul class=\"navbar-nav mx-auto h-100\">\r\n");
      out.write("					<li class=\"nav-item\"><a class=\"nav-link\" href=\"index.html\">\r\n");
      out.write("							<i class=\"fas fa-tachometer-alt\"></i> Dashboard <span\r\n");
      out.write("							class=\"sr-only\">(current)</span>\r\n");
      out.write("					</a></li>\r\n");
      out.write("					<li class=\"nav-item dropdown\"><a\r\n");
      out.write("						class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdown\"\r\n");
      out.write("						role=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\"\r\n");
      out.write("						aria-expanded=\"false\"> <i class=\"far fa-file-alt\"></i> <span>\r\n");
      out.write("								Reports <i class=\"fas fa-angle-down\"></i>\r\n");
      out.write("						</span>\r\n");
      out.write("					</a>\r\n");
      out.write("						<div class=\"dropdown-menu\" aria-labelledby=\"navbarDropdown\">\r\n");
      out.write("							<a class=\"dropdown-item\" href=\"#\">Daily Report</a> <a\r\n");
      out.write("								class=\"dropdown-item\" href=\"#\">Weekly Report</a> <a\r\n");
      out.write("								class=\"dropdown-item\" href=\"#\">Yearly Report</a>\r\n");
      out.write("						</div></li>\r\n");
      out.write("					<li class=\"nav-item\"><a class=\"nav-link active\"\r\n");
      out.write("						href=\"products.html\"> <i class=\"fas fa-shopping-cart\"></i>\r\n");
      out.write("							Products\r\n");
      out.write("					</a></li>\r\n");
      out.write("\r\n");
      out.write("					<li class=\"nav-item\"><a class=\"nav-link\" href=\"accounts.html\">\r\n");
      out.write("							<i class=\"far fa-user\"></i> Accounts\r\n");
      out.write("					</a></li>\r\n");
      out.write("					<li class=\"nav-item dropdown\"><a\r\n");
      out.write("						class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdown\"\r\n");
      out.write("						role=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\"\r\n");
      out.write("						aria-expanded=\"false\"> <i class=\"fas fa-cog\"></i> <span>\r\n");
      out.write("								Settings <i class=\"fas fa-angle-down\"></i>\r\n");
      out.write("						</span>\r\n");
      out.write("					</a>\r\n");
      out.write("						<div class=\"dropdown-menu\" aria-labelledby=\"navbarDropdown\">\r\n");
      out.write("							<a class=\"dropdown-item\" href=\"#\">Profile</a> <a\r\n");
      out.write("								class=\"dropdown-item\" href=\"#\">Billing</a> <a\r\n");
      out.write("								class=\"dropdown-item\" href=\"#\">Customize</a>\r\n");
      out.write("						</div></li>\r\n");
      out.write("				</ul>\r\n");
      out.write("				<ul class=\"navbar-nav\">\r\n");
      out.write("					<li class=\"nav-item\"><a class=\"nav-link d-block\"\r\n");
      out.write("						href=\"login.html\"> Admin, <b>Logout</b>\r\n");
      out.write("					</a></li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</nav>\r\n");
      out.write("	<div class=\"container tm-mt-big tm-mb-big\">\r\n");
      out.write("		<div class=\"row\">\r\n");
      out.write("			<div class=\"col-xl-9 col-lg-10 col-md-12 col-sm-12 mx-auto\">\r\n");
      out.write("				<div class=\"tm-bg-primary-dark tm-block tm-block-h-auto\">\r\n");
      out.write("					<div class=\"row\">\r\n");
      out.write("						<div class=\"col-12\">\r\n");
      out.write("							<h2 class=\"tm-block-title d-inline-block\">Add Product</h2>\r\n");
      out.write("							<div class=\"red\" id=\"baoLoi\">\r\n");
      out.write("			                       ");
      out.print(baoLoi );
      out.write("\r\n");
      out.write("		                    </div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"row tm-edit-product-row\">\r\n");
      out.write("						<div class=\"col-md-12\">\r\n");
      out.write("							<form action=\"San-Pham\" class=\"tm-edit-product-form\" method=\"post\" enctype=\"multipart/form-data\">\r\n");
      out.write("								<input type=\"hidden\" name=\"act\" value=\"them-san-pham\"/>\r\n");
      out.write("								<div class=\"form-group mb-3\">\r\n");
      out.write("									<label for=\"name\">Tên Sản Phẩm </label> <input id=\"tenSanPham\"\r\n");
      out.write("										name=\"tenSanPham\" type=\"text\" class=\"form-control validate\"\r\n");
      out.write("										required />\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"form-group mb-3\">\r\n");
      out.write("									<label for=\"description\">Mô tả</label>\r\n");
      out.write("									<textarea class=\"form-control validate\" rows=\"3\" name=\"moTa\"\r\n");
      out.write("										required></textarea>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"form-group mb-3\">\r\n");
      out.write("									<label for=\"category\">Thể Loại</label> <select\r\n");
      out.write("										class=\"custom-select tm-select-accounts\" id=\"category\"\r\n");
      out.write("										name=\"category\">\r\n");
      out.write("										<option selected>Select category</option>\r\n");
      out.write("										<option value=\"khoaHoc\">Khoa Học</option>\r\n");
      out.write("										<option value=\"vanHoc\">Văn Học</option>\r\n");
      out.write("										<option value=\"doiSong\">Đời Sống</option>\r\n");
      out.write("									</select>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"row\">\r\n");
      out.write("									<div class=\"form-group mb-3 col-xs-12 col-sm-6\">\r\n");
      out.write("										<label for=\"expire_date\">Số Lượng</label> <input id=\"\"\r\n");
      out.write("											name=\"soLuong\" type=\"text\" class=\"form-control validate\"\r\n");
      out.write("											data-large-mode=\"true\" />\r\n");
      out.write("									</div>\r\n");
      out.write("									<div class=\"form-group mb-3 col-xs-12 col-sm-6\">\r\n");
      out.write("										<label for=\"stock\">Giá Bán</label> <input id=\"stock\"\r\n");
      out.write("											name=\"giaBan\" type=\"text\" class=\"form-control validate\"\r\n");
      out.write("											required />\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"row\">\r\n");
      out.write("							<div class=\"col-xl-4 col-lg-4 col-md-4 mx-auto mb-4\">\r\n");
      out.write("								<div class=\"tm-product-img-dummy mx-auto\">\r\n");
      out.write("									<img id=\"uploadedImage1\" src=\"\" alt=\"Uploaded Image 1\"\r\n");
      out.write("										style=\"display: none; max-width: 100%; height: auto;\">\r\n");
      out.write("								</div>\r\n");
      out.write("								<input id=\"fileInput1\" name=\"fileInput1\" type=\"file\"\r\n");
      out.write("									style=\"display: none;\" onchange=\"previewImage(event, 1)\">\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"col-xl-4 col-lg-4 col-md-4 mx-auto mb-4\">\r\n");
      out.write("								<div class=\"tm-product-img-dummy mx-auto\">\r\n");
      out.write("									<img id=\"uploadedImage2\" src=\"\" alt=\"Uploaded Image 2\"\r\n");
      out.write("										style=\"display: none; max-width: 100%; height: auto;\">\r\n");
      out.write("								</div>\r\n");
      out.write("								<input id=\"fileInput2\" name=\"fileInput2\" type=\"file\"\r\n");
      out.write("									style=\"display: none;\" onchange=\"previewImage(event, 2)\">\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"col-xl-4 col-lg-4 col-md-4 mx-auto mb-4\">\r\n");
      out.write("								<div class=\"tm-product-img-dummy mx-auto\">\r\n");
      out.write("									<img id=\"uploadedImage3\" src=\"\" alt=\"Uploaded Image 3\"\r\n");
      out.write("										style=\"display: none; max-width: 100%; height: auto;\">\r\n");
      out.write("								</div>\r\n");
      out.write("								<input id=\"fileInput3\" name=\"fileInput3\" type=\"file\"\r\n");
      out.write("									style=\"display: none;\" onchange=\"previewImage(event, 3)\">\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"row\">\r\n");
      out.write("							<div class=\"col-xl-6 col-lg-6 col-md-12 mx-auto mb-4\">\r\n");
      out.write("								<div class=\"custom-file mt-3 mb-3\">\r\n");
      out.write("									<input type=\"button\" class=\"btn btn-primary btn-block mx-auto\"\r\n");
      out.write("										value=\"Thêm Ảnh\" onclick=\"openFileInput()\">\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"col-12\">\r\n");
      out.write("							<button type=\"submit\"\r\n");
      out.write("								class=\"btn btn-primary btn-block text-uppercase\"\r\n");
      out.write("								value=\"themSanPham\">Thêm Sản Phẩm Ngay</button>\r\n");
      out.write("						</div>\r\n");
      out.write("						</form>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<footer class=\"tm-footer row tm-mt-small\">\r\n");
      out.write("		<div class=\"col-12 font-weight-light\">\r\n");
      out.write("			<p class=\"text-center text-white mb-0 px-4 small\">\r\n");
      out.write("				Copyright &copy; <b>2018</b> All rights reserved. Design: <a\r\n");
      out.write("					rel=\"nofollow noopener\" href=\"https://templatemo.com\"\r\n");
      out.write("					class=\"tm-footer-link\">Template Mo</a>\r\n");
      out.write("			</p>\r\n");
      out.write("		</div>\r\n");
      out.write("	</footer>\r\n");
      out.write("\r\n");
      out.write("	<script src=\"js/jquery-3.3.1.min.js\"></script>\r\n");
      out.write("	<!-- https://jquery.com/download/ -->\r\n");
      out.write("	<script src=\"jquery-ui-datepicker/jquery-ui.min.js\"></script>\r\n");
      out.write("	<!-- https://jqueryui.com/download/ -->\r\n");
      out.write("	<script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("	<!-- https://getbootstrap.com/ -->\r\n");
      out.write("	<script>\r\n");
      out.write("		$(function() {\r\n");
      out.write("			$(\"#expire_date\").datepicker();\r\n");
      out.write("		});\r\n");
      out.write("	</script>\r\n");
      out.write("\r\n");
      out.write("	<script>\r\n");
      out.write("		let currentImageNumber = 1;\r\n");
      out.write("\r\n");
      out.write("		function openFileInput() {\r\n");
      out.write("			if (currentImageNumber <= 3) {\r\n");
      out.write("				document.getElementById('fileInput' + currentImageNumber)\r\n");
      out.write("						.click();\r\n");
      out.write("				currentImageNumber++;\r\n");
      out.write("			}\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		function previewImage(event, imageNumber) {\r\n");
      out.write("			const input = event.target;\r\n");
      out.write("			if (input.files && input.files[0]) {\r\n");
      out.write("				const reader = new FileReader();\r\n");
      out.write("\r\n");
      out.write("				reader.onload = function(e) {\r\n");
      out.write("					const imageId = 'uploadedImage' + imageNumber;\r\n");
      out.write("					const image = document.getElementById(imageId);\r\n");
      out.write("					image.src = e.target.result;\r\n");
      out.write("					image.style.display = 'block';\r\n");
      out.write("				};\r\n");
      out.write("\r\n");
      out.write("				reader.readAsDataURL(input.files[0]);\r\n");
      out.write("			}\r\n");
      out.write("		}\r\n");
      out.write("	</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
