/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.65
 * Generated at: 2023-12-11 21:59:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.khachhang;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import models.KhachHang;

public final class dangky_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/header.jsp", Long.valueOf(1702290484708L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("models.KhachHang");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("<title>Đăng ký</title>\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css\"\r\n");
      out.write("	rel=\"stylesheet\"\r\n");
      out.write("	integrity=\"sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT\"\r\n");
      out.write("	crossorigin=\"anonymous\">\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js\"\r\n");
      out.write("	integrity=\"sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3\"\r\n");
      out.write("	crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.min.js\"\r\n");
      out.write("	integrity=\"sha384-7VPbUDkoPSGFnVtYi0QogXtr74QeVeeIs99Qfg5YCF+TidwNdjvaKZX19NZ/e6oz\"\r\n");
      out.write("	crossorigin=\"anonymous\"></script>\r\n");
      out.write("<style>\r\n");
      out.write(".red {\r\n");
      out.write("	color: red;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<link rel=\"icon\" href=\"logo.png\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write(" ");

 String url = request.getScheme() + "://" + request.getServerName() + ":" + request.getServerPort()
	+ request.getContextPath();
 
      out.write(" \r\n");
      out.write("<!-- Navbar -->\r\n");
      out.write("	<nav class=\"navbar navbar-expand-lg bg-light\">\r\n");
      out.write("		<div class=\"container-fluid\">\r\n");
      out.write("			<a class=\"navbar-brand\" href=\"#\"> <img\r\n");
      out.write("				src=\"img/logo/logo.png\"\r\n");
      out.write("				alt=\"Bootstrap\" height=\"30\">\r\n");
      out.write("			</a>\r\n");
      out.write("			<button class=\"navbar-toggler\" type=\"button\"\r\n");
      out.write("				data-bs-toggle=\"collapse\" data-bs-target=\"#navbarSupportedContent\"\r\n");
      out.write("				aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\"\r\n");
      out.write("				aria-label=\"Toggle navigation\">\r\n");
      out.write("				<span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("			</button>\r\n");
      out.write("			<div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\r\n");
      out.write("				<ul class=\"navbar-nav me-auto mb-2 mb-lg-0\">\r\n");
      out.write("					<li class=\"nav-item\"><a class=\"nav-link active\"\r\n");
      out.write("						aria-current=\"page\" href=\"index.jsp\">Trang chủ</a></li>\r\n");
      out.write("					<li class=\"nav-item\"><a class=\"nav-link\" href=\"#\">Combo\r\n");
      out.write("							giảm giá</a></li>\r\n");
      out.write("					<li class=\"nav-item dropdown\"><a\r\n");
      out.write("						class=\"nav-link dropdown-toggle\" href=\"#\" role=\"button\"\r\n");
      out.write("						data-bs-toggle=\"dropdown\" aria-expanded=\"false\"> Thể loại </a>\r\n");
      out.write("						<ul class=\"dropdown-menu\">\r\n");
      out.write("							<li><a class=\"dropdown-item\" href=\"khoahoc.jsp\">Khoa Học</a></li>\r\n");
      out.write("							<li><a class=\"dropdown-item\" href=\"vanhoc.jsp\">Văn Học</a></li>\r\n");
      out.write("							<li><hr class=\"dropdown-divider\"></li>\r\n");
      out.write("							<li><a class=\"dropdown-item\" href=\"doisong.jsp\">Đời Sống</a></li>\r\n");
      out.write("						</ul></li>\r\n");
      out.write("					<li class=\"nav-item\"><a class=\"nav-link disabled\">Hết hàng</a>\r\n");
      out.write("					</li>\r\n");
      out.write("				</ul>\r\n");
      out.write("				<form class=\"d-flex\" role=\"search\" style=\"position: relative;display: block;float: right;\">\r\n");
      out.write("					<input class=\"form-control me-2\" type=\"search\"\r\n");
      out.write("						placeholder=\"Nội dung tìm kiếm\" aria-label=\"Search\">\r\n");
      out.write("					<button class=\"btn btn-outline-success\" type=\"submit\">Tìm</button>\r\n");
      out.write("					");

						Object obj = session.getAttribute("khachHang");
						KhachHang khachHang = null;
						if (obj!=null)
							khachHang = (KhachHang)obj;
						
						if(khachHang==null){
					
      out.write("\r\n");
      out.write("						<a class=\"btn btn-primary\" style=\"white-space: nowrap;\" href=\"khachhang/dangnhap.jsp\">\r\n");
      out.write("							Đăng nhập\r\n");
      out.write("						</a>\r\n");
      out.write("					");
} else { 
      out.write("\r\n");
      out.write("					<ul class=\"navbar-nav me-auto mb-2 mb-lg-0 bg-infor \">\r\n");
      out.write("						<li class=\"nav-item dropdown dropstart\"><a\r\n");
      out.write("							class=\"nav-link dropdown-toggle\" href=\"#\" role=\"button\"\r\n");
      out.write("							data-bs-toggle=\"dropdown\" aria-expanded=\"false\"> Tài khoản</a>\r\n");
      out.write("							<ul class=\"dropdown-menu\">\r\n");
      out.write("								<li><a class=\"dropdown-item\" href=\"#\">Đơn hàng của tôi</a></li>\r\n");
      out.write("								<li><a class=\"dropdown-item\" href=\"#\">Thông báo</a></li>\r\n");
      out.write("								<li><a class=\"dropdown-item\" href=\"");
      out.print(url );
      out.write("/khachhang/thaydoianh.jsp\">Thay đổi ảnh avatar</a></li>\r\n");
      out.write("								<li><a class=\"dropdown-item\" href=\"");
      out.print(url );
      out.write("/khachhang/thaydoithongtin.jsp\">Thay đổi thông tin</a></li>\r\n");
      out.write("								<li><a class=\"dropdown-item\" href=\"");
      out.print(url );
      out.write("/khachhang/doimatkhau.jsp\">Đổi mật khẩu</a></li>\r\n");
      out.write("								<li><hr class=\"dropdown-divider\"></li>\r\n");
      out.write("								<li><a class=\"dropdown-item\" href=\"");
      out.print(url );
      out.write("/khach-hang?hanhDong=dang-xuat\">Thoát tài khoản</a></li>\r\n");
      out.write("							</ul></li>\r\n");
      out.write("					</ul>				\r\n");
      out.write("						\r\n");
      out.write("					");
 } 
      out.write("\r\n");
      out.write("				</form>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</nav>\r\n");
      out.write("	<!-- End Navbar -->");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	");

		String baoLoi = request.getAttribute("baoLoi")+"";
		baoLoi = (baoLoi.equals("null"))?"":baoLoi;
	
		
		String tenDangNhap= request.getAttribute("tenDangNhap")+"";	
		tenDangNhap = (tenDangNhap.equals("null"))?"":tenDangNhap;
		
		String hoVaTen= request.getAttribute("hoVaTen")+"";
		hoVaTen = (hoVaTen.equals("null"))?"":hoVaTen;
		
		String gioiTinh= request.getAttribute("gioiTinh")+"";
		gioiTinh = (gioiTinh.equals("null"))?"":gioiTinh;
		
		String ngaySinh= request.getAttribute("ngaySinh")+"";
		ngaySinh = (ngaySinh.equals("null"))?"":ngaySinh;
		
		String diaChiKhachHang= request.getAttribute("diaChiKhachHang")+"";
		diaChiKhachHang = (diaChiKhachHang.equals("null"))?"":diaChiKhachHang;
		
		String diaChiMuaHang= request.getAttribute("diaChiMuaHang")+"";
		diaChiMuaHang = (diaChiMuaHang.equals("null"))?"":diaChiMuaHang;
		
		String diaChiNhanHang= request.getAttribute("diaChiNhanHang")+"";
		diaChiNhanHang = (diaChiNhanHang.equals("null"))?"":diaChiNhanHang;
		
		String dienThoai= request.getAttribute("dienThoai")+"";
		dienThoai = (dienThoai.equals("null"))?"":dienThoai;
		
		String email= request.getAttribute("email")+"";
		email = (email.equals("null"))?"":email;
		
		String dongYNhanMail= request.getAttribute("dongYNhanMail")+"";
		dongYNhanMail = (dongYNhanMail.equals("null"))?"":dongYNhanMail;
	
      out.write("\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("		<div class=\"text-center\">\r\n");
      out.write("			<h1>ĐĂNG KÝ TÀI KHOẢN</h1>\r\n");
      out.write("		</div>\r\n");
      out.write("		\r\n");
      out.write("		<div class=\"red\" id=\"baoLoi\">\r\n");
      out.write("			");
      out.print(baoLoi );
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("		 ");

		 String url1 = request.getScheme() + "://" + request.getServerName() + ":" + request.getServerPort()
			+ request.getContextPath();
		 
      out.write("\r\n");
      out.write("		<form class=\"form\" action=\"");
      out.print(url1 );
      out.write("/khach-hang\" method=\"post\">\r\n");
      out.write("			<input type=\"hidden\" name=\"hanhDong\" value=\"dang-ky\"/>\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("				<div class=\"col-sm-6\">\r\n");
      out.write("					<h3>Tài khoản</h3>\r\n");
      out.write("					<div class=\"mb-3\">\r\n");
      out.write("						<label for=\"tenDangNhap\" class=\"form-label\">Tên đăng nhập<span\r\n");
      out.write("							class=\"red\">*</span></label> <input type=\"text\" class=\"form-control\"\r\n");
      out.write("							id=\"tenDangNhap\" name=\"tenDangNhap\" required=\"required\" value=\"");
      out.print(tenDangNhap);
      out.write("\">\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"mb-3\">\r\n");
      out.write("						<label for=\"matKhau\" class=\"form-label\">Mật khẩu<span\r\n");
      out.write("							class=\"red\">*</span></label> <input type=\"password\" class=\"form-control\"\r\n");
      out.write("							id=\"matKhau\" name=\"matKhau\" required=\"required\" onkeyup=\"kiemTraMatKhau()\">\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"mb-3\">\r\n");
      out.write("						<label for=\"matKhauNhapLai\" class=\"form-label\" >Nhập lại\r\n");
      out.write("							mật khẩu<span class=\"red\">*</span> <span id=\"msg\" class=\"red\" ></span>\r\n");
      out.write("						</label> <input type=\"password\" class=\"form-control\" id=\"matKhauNhapLai\"\r\n");
      out.write("							name=\"matKhauNhapLai\" required=\"required\" onkeyup=\"kiemTraMatKhau()\">\r\n");
      out.write("					</div>\r\n");
      out.write("					<hr />\r\n");
      out.write("					<h3>Thông tin khách hàng</h3>\r\n");
      out.write("					<div class=\"mb-3\">\r\n");
      out.write("						<label for=\"hoVaTen\" class=\"form-label\">Họ và tên</label> <input\r\n");
      out.write("							type=\"text\" class=\"form-control\" id=\"hoVaTen\" name=\"hoVaTen\" value=\"");
      out.print(hoVaTen);
      out.write("\">\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"mb-3\">\r\n");
      out.write("						<label for=\"gioiTinh\" class=\"form-label\">Giới tính</label> <select\r\n");
      out.write("							class=\"form-control\" id=\"gioiTinh\" name=\"gioiTinh\">\r\n");
      out.write("							<option></option>\r\n");
      out.write("							<option value=\"Nam\" ");
      out.print((gioiTinh.equals("Nam"))?"selected='selected'":"" );
      out.write(" >Nam</option>\r\n");
      out.write("							<option value=\"Nữ\" ");
      out.print((gioiTinh.equals("Nữ"))?"selected='selected'":"" );
      out.write(" >Nữ</option>\r\n");
      out.write("							<option value=\"Khác\" ");
      out.print((gioiTinh.equals("Khác"))?"selected='selected'":"" );
      out.write(" >Khác</option>\r\n");
      out.write("						</select>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"mb-3\">\r\n");
      out.write("						<label for=\"ngaySinh\" class=\"form-label\">Ngày sinh</label> <input\r\n");
      out.write("							type=\"date\" class=\"form-control\" id=\"ngaySinh\" name=\"ngaySinh\" value=\"");
      out.print(ngaySinh);
      out.write("\">\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-sm-6\">\r\n");
      out.write("					<h3>Địa chỉ</h3>\r\n");
      out.write("					<div class=\"mb-3\">\r\n");
      out.write("						<label for=\"diaChiKhachHang\" class=\"form-label\">Địa chỉ\r\n");
      out.write("							khách hàng</label> <input type=\"text\" class=\"form-control\"\r\n");
      out.write("							id=\"diaChiKhachHang\" name=\"diaChiKhachHang\" value=\"");
      out.print(diaChiKhachHang);
      out.write("\">\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"mb-3\">\r\n");
      out.write("						<label for=\"diaChiMuaHang\" class=\"form-label\">Địa chỉ mua\r\n");
      out.write("							hàng</label> <input type=\"text\" class=\"form-control\" id=\"diaChiMuaHang\"\r\n");
      out.write("							name=\"diaChiMuaHang\" value=\"");
      out.print(diaChiMuaHang);
      out.write("\">\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"mb-3\">\r\n");
      out.write("						<label for=\"diaChiNhanHang\" class=\"form-label\">Địa chỉ\r\n");
      out.write("							nhận hàng</label> <input type=\"text\" class=\"form-control\"\r\n");
      out.write("							id=\"diaChiNhanHang\" name=\"diaChiNhanHang\" value=\"");
      out.print(diaChiNhanHang);
      out.write("\">\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"mb-3\">\r\n");
      out.write("						<label for=\"dienThoai\" class=\"form-label\">Điện thoại</label> <input\r\n");
      out.write("							type=\"tel\" class=\"form-control\" id=\"dienThoai\" name=\"dienThoai\" value=\"");
      out.print(dienThoai);
      out.write("\">\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"mb-3\">\r\n");
      out.write("						<label for=\"email\" class=\"form-label\">Email</label> <input\r\n");
      out.write("							type=\"email\" class=\"form-control\" id=\"email\" name=\"email\"  value=\"");
      out.print(email);
      out.write("\">\r\n");
      out.write("					</div>\r\n");
      out.write("					<hr />\r\n");
      out.write("					<div class=\"mb-3\">\r\n");
      out.write("						<label for=\"dongYDieuKhoan\" class=\"form-label\">Đồng ý với\r\n");
      out.write("							<a>điều khoản của công ty </a><span id=\"red\">*</span>\r\n");
      out.write("						</label> <input type=\"checkbox\" class=\"form-check-input\"\r\n");
      out.write("							id=\"dongYDieuKhoan\" name=\"dongYDieuKhoan\" required=\"required\" onchange=\"xuLyChonDongY()\">\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"mb-3\">\r\n");
      out.write("						<label for=\"dongYNhanMail\" class=\"form-label\">Đồng ý nhận\r\n");
      out.write("							email</label> <input type=\"checkbox\" class=\"form-check-input\"\r\n");
      out.write("							id=\"dongYNhanMail\" name=\"dongYNhanMail\">\r\n");
      out.write("					</div>\r\n");
      out.write("					<input class=\"btn btn-primary form-control\" type=\"submit\"\r\n");
      out.write("						value=\"Đăng ký\" name=\"submit\" id=\"submit\" style=\"visibility: hidden;\" />\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</form>\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../footer.jsp", out, false);
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("	function kiemTraMatKhau(){\r\n");
      out.write("		matKhau = document.getElementById(\"matKhau\").value;\r\n");
      out.write("		matKhauNhapLai = document.getElementById(\"matKhauNhapLai\").value;\r\n");
      out.write("		if(matKhau!=matKhauNhapLai){\r\n");
      out.write("			document.getElementById(\"msg\").innerHTML = \"Mật khẩu không khớp!\";\r\n");
      out.write("			return false;\r\n");
      out.write("		}else{\r\n");
      out.write("			document.getElementById(\"msg\").innerHTML = \"\";\r\n");
      out.write("			return true;\r\n");
      out.write("		}\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	function xuLyChonDongY(){\r\n");
      out.write("		dongYDeuKhoan = document.getElementById(\"dongYDieuKhoan\");\r\n");
      out.write("		if(dongYDeuKhoan.checked==true){\r\n");
      out.write("			document.getElementById(\"submit\").style.visibility=\"visible\";\r\n");
      out.write("		} else {\r\n");
      out.write("			document.getElementById(\"submit\").style.visibility=\"hidden\";\r\n");
      out.write("		}\r\n");
      out.write("	}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
