/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.65
 * Generated at: 2023-12-11 07:05:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.khachhang;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class detailproduct_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<title>Single E-commerce Product Page using HTML, CSS -\r\n");
      out.write("	Codingscape</title>\r\n");
      out.write("<!-- Stylesheet -->\r\n");
      out.write("<!---Boxicons CDN Setup for icons-->\r\n");
      out.write("<link href='https://unpkg.com/boxicons@2.1.2/css/boxicons.min.css'\r\n");
      out.write("	rel='stylesheet'>\r\n");
      out.write("<style>\r\n");
      out.write("@import\r\n");
      out.write("	url('https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700&display=swap')\r\n");
      out.write("	; /** Poppins Font **/\r\n");
      out.write("\r\n");
      out.write("/** gobal layout */\r\n");
      out.write("* {\r\n");
      out.write("	padding: 0;\r\n");
      out.write("	margin: 0;\r\n");
      out.write("	box-sizing: border-box;\r\n");
      out.write("	font-family: 'Poppins', sans-serif;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(":root {\r\n");
      out.write("	--primary-color: #5344db;\r\n");
      out.write("	--accent-color: #5344db;\r\n");
      out.write("	--grey: #484848;\r\n");
      out.write("	--bg-grey: #efefef;\r\n");
      out.write("	--shadow: #949494;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".container {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	position: relative;\r\n");
      out.write("	align-items: center;\r\n");
      out.write("	justify-content: center;\r\n");
      out.write("	height: 100vh;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".row {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	gap: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".col-6 {\r\n");
      out.write("	width: 50%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".single-product {\r\n");
      out.write("	width: 1080px;\r\n");
      out.write("	position: relative;\r\n");
      out.write("}\r\n");
      out.write("/** Breadcrumb **/\r\n");
      out.write(".single-product .breadcrumb {\r\n");
      out.write("	background: #48484810;\r\n");
      out.write("	padding: 8px 4px;\r\n");
      out.write("	border-radius: 8px;\r\n");
      out.write("	font-size: 15px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".breadcrumb span {\r\n");
      out.write("	display: inline-flex;\r\n");
      out.write("	flex-direction: row;\r\n");
      out.write("	gap: 8px;\r\n");
      out.write("	margin-left: 8px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".breadcrumb span:not(:last-child)::after {\r\n");
      out.write("	content: '/';\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".breadcrumb span a {\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("	color: var(--primary-color);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/** product image **/\r\n");
      out.write(".single-product .product-image {\r\n");
      out.write("	width: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".product-image .product-image-main {\r\n");
      out.write("	position: relative;\r\n");
      out.write("	display: block;\r\n");
      out.write("	height: 480px;\r\n");
      out.write("	background: var(--bg-grey);\r\n");
      out.write("	padding: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".product-image-main img {\r\n");
      out.write("	display: block;\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	height: 100%;\r\n");
      out.write("	object-fit: contain;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".product-image-slider {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	gap: 10px;\r\n");
      out.write("	margin: 10px 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".product-image-slider img {\r\n");
      out.write("	width: 90px;\r\n");
      out.write("	height: 90px;\r\n");
      out.write("	background: var(--bg-grey);\r\n");
      out.write("	padding: 6px;\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/** product title **/\r\n");
      out.write(".product-title {\r\n");
      out.write("	margin-top: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".product-title h2 {\r\n");
      out.write("	font-size: 32px;\r\n");
      out.write("	line-height: 2.4rem;\r\n");
      out.write("	font-weight: 700;\r\n");
      out.write("	letter-spacing: -0.02rem;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/** product rating **/\r\n");
      out.write(".product-rating {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	margin-top: 4px;\r\n");
      out.write("	margin-bottom: 10px;\r\n");
      out.write("	align-items: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".product-rating span:not(:last-child) {\r\n");
      out.write("	color: #ffc600;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".product-rating .review {\r\n");
      out.write("	color: var(--grey);\r\n");
      out.write("	font-size: 12px;\r\n");
      out.write("	font-weight: 500;\r\n");
      out.write("}\r\n");
      out.write("/** Product price **/\r\n");
      out.write(".product-price {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	position: relative;\r\n");
      out.write("	margin: 10px 0;\r\n");
      out.write("	align-items: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".product-price .offer-price {\r\n");
      out.write("	font-size: 48px;\r\n");
      out.write("	font-weight: 700;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".product-price .sale-price {\r\n");
      out.write("	font-size: 22px;\r\n");
      out.write("	font-weight: 500;\r\n");
      out.write("	text-decoration: line-through;\r\n");
      out.write("	color: var(--grey);\r\n");
      out.write("	margin-left: 12px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/** Product Details **/\r\n");
      out.write(".product-details {\r\n");
      out.write("	margin: 10px 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".product-details h3 {\r\n");
      out.write("	font-size: 18px;\r\n");
      out.write("	font-weight: 500;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".product-details p {\r\n");
      out.write("	margin: 5px 0;\r\n");
      out.write("	font-size: 14px;\r\n");
      out.write("	line-height: 1.2rem;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/** Product size **/\r\n");
      out.write(".product-size {\r\n");
      out.write("	margin: 10px 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".product-size h4 {\r\n");
      out.write("	font-size: 16px;\r\n");
      out.write("	font-weight: 500;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".product-size .size-layout {\r\n");
      out.write("	margin: 5px 0;\r\n");
      out.write("	display: inline-flex;\r\n");
      out.write("	align-items: center;\r\n");
      out.write("	gap: 10px;\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".product-size .size-layout .size-input {\r\n");
      out.write("	display: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".product-size .size-layout .size {\r\n");
      out.write("	background: var(--bg-grey);\r\n");
      out.write("	padding: 10px 18px;\r\n");
      out.write("	border: 1px solid var(--bg-grey);\r\n");
      out.write("	border-radius: 4px;\r\n");
      out.write("	margin-left: 0px;\r\n");
      out.write("	font-size: 16px;\r\n");
      out.write("	font-weight: 700;\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".product-size .size-layout .size:hover {\r\n");
      out.write("	border: 1px solid var(--grey);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".product-size .size-layout input[type=\"radio\"]:checked+.size {\r\n");
      out.write("	background-color: rgb(35, 35, 35);\r\n");
      out.write("	border: 1px solid var(--grey);\r\n");
      out.write("	color: var(--bg-grey);\r\n");
      out.write("	box-shadow: 0 3px 6px var(--shadow);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/** Product Color **/\r\n");
      out.write(".product-color {\r\n");
      out.write("	margin: 10px 0;\r\n");
      out.write("	justify-content: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".product-color h4 {\r\n");
      out.write("	font-size: 16px;\r\n");
      out.write("	font-weight: 500;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".product-color .color-layout {\r\n");
      out.write("	margin: 5px 0;\r\n");
      out.write("	display: flex;\r\n");
      out.write("	gap: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".product-color .color-layout label {\r\n");
      out.write("	border-radius: 4px;\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("	content: '';\r\n");
      out.write("	width: 40px;\r\n");
      out.write("	height: 40px;\r\n");
      out.write("	display: inline-block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".product-color .color-layout .black {\r\n");
      out.write("	background-color: black;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".product-color .color-layout .red {\r\n");
      out.write("	background-color: red;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".product-color .color-layout .blue {\r\n");
      out.write("	background-color: blue;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".product-color .color-layout input[type=\"radio\"]:checked+label {\r\n");
      out.write("	box-shadow: 0 3px 6px var(--shadow);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".product-color .color-layout .color-input {\r\n");
      out.write("	display: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/** divider **/\r\n");
      out.write(".divider {\r\n");
      out.write("	display: block;\r\n");
      out.write("	height: 1px;\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	background: #48484830;\r\n");
      out.write("	margin: 20px 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/** product Button Group **/\r\n");
      out.write(".product-btn-group {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	gap: 15px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".product-btn-group .button {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	align-items: center;\r\n");
      out.write("	justify-content: center;\r\n");
      out.write("	gap: 4px;\r\n");
      out.write("	padding: 10px 24px;\r\n");
      out.write("	font-size: 16px;\r\n");
      out.write("	font-weight: 500;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".product-btn-group .buy-now {\r\n");
      out.write("	background-color: var(--accent-color);\r\n");
      out.write("	color: #fff;\r\n");
      out.write("	border: 1px solid var(--accent-color);\r\n");
      out.write("	border-radius: 4px;\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".product-btn-group .buy-now i {\r\n");
      out.write("	font-size: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".product-btn-group .buy-now:hover {\r\n");
      out.write("	box-shadow: 0 3px 6px var(--shadow);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".product-btn-group .add-cart {\r\n");
      out.write("	background-color: var(--bg-grey);\r\n");
      out.write("	color: var(--grey);\r\n");
      out.write("	border-radius: 4px;\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".product-btn-group .add-cart i {\r\n");
      out.write("	font-size: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".product-btn-group .add-cart:hover {\r\n");
      out.write("	box-shadow: 0 3px 6px var(--shadow);\r\n");
      out.write("	background: var(--grey);\r\n");
      out.write("	color: #fff;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".product-btn-group .heart {\r\n");
      out.write("	color: var(--grey);\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".product-btn-group .heart i {\r\n");
      out.write("	font-size: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".product-btn-group .heart:hover {\r\n");
      out.write("	color: var(--accent-color);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/** Responsive Mobile **/\r\n");
      out.write("@media screen and (max-width:520px) {\r\n");
      out.write("	.container {\r\n");
      out.write("		padding: 20px;\r\n");
      out.write("		height: auto;\r\n");
      out.write("	}\r\n");
      out.write("	.row {\r\n");
      out.write("		display: block;\r\n");
      out.write("	}\r\n");
      out.write("	.col-6 {\r\n");
      out.write("		width: 100%;\r\n");
      out.write("		display: block;\r\n");
      out.write("	}\r\n");
      out.write("	.single-product {\r\n");
      out.write("		width: 100%;\r\n");
      out.write("		position: relative;\r\n");
      out.write("	}\r\n");
      out.write("	.product-image .product-image-main {\r\n");
      out.write("		width: 100%;\r\n");
      out.write("		height: 280px;\r\n");
      out.write("	}\r\n");
      out.write("	.product-image-slider {\r\n");
      out.write("		gap: 5px;\r\n");
      out.write("	}\r\n");
      out.write("	.breadcrumb {\r\n");
      out.write("		display: none;\r\n");
      out.write("	}\r\n");
      out.write("	.product-title h2 {\r\n");
      out.write("		font-size: 24px;\r\n");
      out.write("		line-height: 1.6rem;\r\n");
      out.write("	}\r\n");
      out.write("	.product-size {\r\n");
      out.write("		display: block;\r\n");
      out.write("	}\r\n");
      out.write("	.product-size .size-layout {\r\n");
      out.write("		display: block;\r\n");
      out.write("		margin: 10px 0;\r\n");
      out.write("	}\r\n");
      out.write("	.product-size .size-layout .size {\r\n");
      out.write("		padding: 6px 10px;\r\n");
      out.write("	}\r\n");
      out.write("	.product-btn-group {\r\n");
      out.write("		display: flex;\r\n");
      out.write("		flex-direction: column;\r\n");
      out.write("		gap: 10px;\r\n");
      out.write("	}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/** Responsive Tablet **/\r\n");
      out.write("@media ( min-width : 520px ) and (max-width: 1080px) {\r\n");
      out.write("	.container {\r\n");
      out.write("		display: block;\r\n");
      out.write("		height: auto;\r\n");
      out.write("		padding: 20px;\r\n");
      out.write("	}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("106434\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".9609  \r\n");
      out.write("\r\n");
      out.write(".row {\r\n");
      out.write("	width: 130%;\r\n");
      out.write("	display: flex;\r\n");
      out.write("	gap: 20px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("		<div class=\"single-product\">\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("				<div class=\"col-6\">\r\n");
      out.write("					<div class=\"product-image\">\r\n");
      out.write("						<div class=\"product-image-main\">\r\n");
      out.write("							<img\r\n");
      out.write("								src=\"http://static.nhanam.com.vn/thumb/0x320/crop/Books/Images/2019/5/7/78GAAPI9.jpg\"\r\n");
      out.write("								alt=\"\" id=\"product-main-image\">\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"product-image-slider\">\r\n");
      out.write("							<img\r\n");
      out.write("								src=\"https://product.hstatic.net/1000328521/product/hoang_tu_be_tb_3d_thumb_inside_1_bfd151290d2945db86d24f034ebed7bb_master.jpg\"\r\n");
      out.write("								alt=\"\" class=\"image-list\"> <img\r\n");
      out.write("								src=\"https://product.hstatic.net/1000328521/product/hoang_tu_be_tb_3d_thumb_inside_2_2bdb33de62ca43de8bcf024fe1ab8c3c_master.jpg\"\r\n");
      out.write("								alt=\"\" class=\"image-list\"> <img\r\n");
      out.write("								src=\"https://product.hstatic.net/1000328521/product/hoang_tu_be_tb_3d_thumb_inside_3_249a25ee7334483bb59a77194bd6e990_master.jpg\"\r\n");
      out.write("								alt=\"\" class=\"image-list\"> <img\r\n");
      out.write("								src=\"https://product.hstatic.net/1000328521/product/hoang_tu_be_tb_3d_thumb_inside_4_152518abaed94b4caefa1cc72d9fe167_master.jpg\"\r\n");
      out.write("								alt=\"\" class=\"image-list\">\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-6\">\r\n");
      out.write("					<div class=\"breadcrumb\">\r\n");
      out.write("						<span><a href=\"index.jsp\">Trang Chủ</a></span> <span><a href=\"#\">Văn Học</a></span>\r\n");
      out.write("						<span class=\"active\">Hoàng Tử Bé</span>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("					<div class=\"product\">\r\n");
      out.write("						<div class=\"product-title\">\r\n");
      out.write("							<h2>HOÀNG TỬ BÉ</h2>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"product-rating\">\r\n");
      out.write("							<span><i class=\"bx bxs-star\"></i></span> <span><i\r\n");
      out.write("								class=\"bx bxs-star\"></i></span> <span><i class=\"bx bxs-star\"></i></span>\r\n");
      out.write("							<span><i class=\"bx bxs-star\"></i></span> <span><i\r\n");
      out.write("								class=\"bx bxs-star\"></i></span> <span class=\"review\">(47 Review)</span>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"product-price\">\r\n");
      out.write("							<span class=\"offer-price\">78,400 đ</span> <span\r\n");
      out.write("								class=\"sale-price\">150,000đ</span>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("			\r\n");
      out.write("						<div class=\"product-details\">\r\n");
      out.write("							<h3>Nội dung giới thiệu</h3>\r\n");
      out.write("							<p><strong>Hoàng Tử Bé</strong>-Kể về một hoàng tử nhỏ cô đơn từ tiểu tinh cầu xa xôi\r\n");
      out.write("								viếng thăm rồi lại lìa xa Trái Đất, Hoàng tử bé được xem là một\r\n");
      out.write("								trong những tác phẩm thơ mộng nhất của mọi thời đại. Cho đến\r\n");
      out.write("								nay, tác phẩm ra đời vào năm 1943 của nhà văn Saint - Exupéry\r\n");
      out.write("								này đã được dịch sang hơn 300 ngôn ngữ và phát hành hơn 140\r\n");
      out.write("								triệu bản trên khắp thế giới. Sự giản dị, trong sáng tỏa khắp\r\n");
      out.write("								tác phẩm đã khiến nó trở thành một bài thơ bất hủ mà mãi mãi\r\n");
      out.write("								người ta muốn đem làm quà tặng của tình yêu. Cuốn sách kinh điển\r\n");
      out.write("								của Saint - Exupéry đã được Đông A tái bản, với bản dịch của\r\n");
      out.write("								dịch giả Vĩnh Lạc được yêu thích bởi ngôn từ giàu tình cảm và\r\n");
      out.write("								trong sáng.</p>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"product-details\">\r\n");
      out.write("							<h3>Thông tin tác giả</h3>\r\n");
      out.write("							<p>Antoine de Saint - Exupéry (1900 - 1944) trong một gia\r\n");
      out.write("								đình quý tộc địa phương ở Lyon, Pháp. Năm 1921, ông nhập ngũ và\r\n");
      out.write("								được gửi đến Strasbourg để học nghề phi công. Năm 1926, ông làm\r\n");
      out.write("								việc cho một công ty vận chuyển bưu phẩm bằng đường hàng không.\r\n");
      out.write("								Những kinh nghiệm và những tai nạn mà ông gặp phải trong khi làm\r\n");
      out.write("								phi công là cảm hứng cho nhiều sáng tác của ông, từ tác phẩm đầu\r\n");
      out.write("								tay Người phi công (L'aviateur, 1926) đến Chuyến thư miền Nam\r\n");
      out.write("								(Courrier Sub, 1929), Bay đêm (Vol de Nuit, 1931) và nhiều tác\r\n");
      out.write("								phẩm khác, đặc biệt là tác phẩm được biết đến nhiều nhất của ông\r\n");
      out.write("								- Hoàng tử bé (Le Petit Prince, 1943). Ngày 31 tháng 7 năm 1944,\r\n");
      out.write("								ông lái máy bay đi làm nhiệm vụ, cất cánh từ đảo Corse của Pháp\r\n");
      out.write("								và không bao giờ trở về nữa.</p>\r\n");
      out.write("						</div>\r\n");
      out.write("						<span class=\"divider\"></span>\r\n");
      out.write("\r\n");
      out.write("						<div class=\"product-btn-group\">\r\n");
      out.write("							<div class=\"button buy-now\">\r\n");
      out.write("								<i class='bx bxs-zap'></i> Buy Now\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"button add-cart\">\r\n");
      out.write("								<i class='bx bxs-cart'></i> Add to Cart\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"button heart\">\r\n");
      out.write("								<i class='bx bxs-heart'></i> Add to Wishlist\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<!--script-->\r\n");
      out.write("	<script>\r\n");
      out.write("		const sliderMainImage = document.getElementById(\"product-main-image\"); //product container image\r\n");
      out.write("		const sliderImageList = document.getElementsByClassName(\"image-list\"); // image thumblian group selection\r\n");
      out.write("		console.log(sliderImageList);\r\n");
      out.write("\r\n");
      out.write("		sliderImageList[0].onclick = function() {\r\n");
      out.write("			sliderMainImage.src = sliderImageList[0].src;\r\n");
      out.write("			console.log(sliderMainImage.src);\r\n");
      out.write("		};\r\n");
      out.write("\r\n");
      out.write("		sliderImageList[1].onclick = function() {\r\n");
      out.write("			sliderMainImage.src = sliderImageList[1].src;\r\n");
      out.write("			console.log(sliderMainImage.src);\r\n");
      out.write("		};\r\n");
      out.write("\r\n");
      out.write("		sliderImageList[2].onclick = function() {\r\n");
      out.write("			sliderMainImage.src = sliderImageList[2].src;\r\n");
      out.write("			console.log(sliderMainImage.src);\r\n");
      out.write("		};\r\n");
      out.write("\r\n");
      out.write("		sliderImageList[3].onclick = function() {\r\n");
      out.write("			sliderMainImage.src = sliderImageList[3].src;\r\n");
      out.write("			console.log(sliderMainImage.src);\r\n");
      out.write("		};\r\n");
      out.write("	</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
