/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.65
 * Generated at: 2023-12-11 17:13:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.khachhang;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import models.KhachHang;

public final class thaydoithongtin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("models.KhachHang");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("<title>Thông tin</title>\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css\"\r\n");
      out.write("	rel=\"stylesheet\"\r\n");
      out.write("	integrity=\"sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT\"\r\n");
      out.write("	crossorigin=\"anonymous\">\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js\"\r\n");
      out.write("	integrity=\"sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3\"\r\n");
      out.write("	crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.min.js\"\r\n");
      out.write("	integrity=\"sha384-7VPbUDkoPSGFnVtYi0QogXtr74QeVeeIs99Qfg5YCF+TidwNdjvaKZX19NZ/e6oz\"\r\n");
      out.write("	crossorigin=\"anonymous\"></script>\r\n");
      out.write("<style>\r\n");
      out.write(".red {\r\n");
      out.write("	color: red;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../header.jsp", out, false);
      out.write('\r');
      out.write('\n');
      out.write('	');

		Object obj = session.getAttribute("khachHang");
		KhachHang khachHang = null;
		if (obj!=null)
			khachHang = (KhachHang)obj;		
			if(khachHang==null){		
	
      out.write("\r\n");
      out.write("	<h1>Bạn chưa đăng nhập vào hệ thống. Vui lòng quay lại trang chủ!</h1>\r\n");
      out.write("	");

			}else {
				
	
      out.write("\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("	");

		String baoLoi = request.getAttribute("baoLoi")+"";
		baoLoi = (baoLoi.equals("null"))?"":baoLoi;
		
		String hoVaTen= khachHang.getHoVaTen();
		
		String gioiTinh= khachHang.getGioiTinh();
		
		String ngaySinh= khachHang.getNgaySinh().toString();
		
		String diaChiKhachHang= khachHang.getDiaChi();
		
		String diaChiMuaHang= khachHang.getDiaChiMuaHang();
		
		String diaChiNhanHang= khachHang.getDiaChiNhanHang();
		
		String dienThoai= khachHang.getSoDienThoai();
		
		String email= khachHang.getEmail();
		
		boolean dongYNhanMail= khachHang.isDangKyNhanBangTin();
	
      out.write("\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("		<div class=\"text-center\">\r\n");
      out.write("			<h1>THÔNG TIN TÀI KHOẢN</h1>\r\n");
      out.write("		</div>\r\n");
      out.write("		\r\n");
      out.write("		<div class=\"red\" id=\"baoLoi\">\r\n");
      out.write("			");
      out.print(baoLoi );
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("		");

		 String url1 = request.getScheme() + "://" + request.getServerName() + ":" + request.getServerPort()
			+ request.getContextPath();
		 
      out.write("\r\n");
      out.write("		<form class=\"form\" action=\"");
      out.print(url1 );
      out.write("/khach-hang\" method=\"post\">\r\n");
      out.write("			<input type=\"hidden\" name=\"hanhDong\" value=\"thay-doi-thong-tin\"/>\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("				<div class=\"col-sm-6\">\r\n");
      out.write("					\r\n");
      out.write("					<h3>Thông tin khách hàng</h3>\r\n");
      out.write("					<div class=\"mb-3\">\r\n");
      out.write("						<label for=\"hoVaTen\" class=\"form-label\">Họ và tên</label> <input\r\n");
      out.write("							type=\"text\" class=\"form-control\" id=\"hoVaTen\" name=\"hoVaTen\" value=\"");
      out.print(hoVaTen);
      out.write("\">\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"mb-3\">\r\n");
      out.write("						<label for=\"gioiTinh\" class=\"form-label\">Giới tính</label> <select\r\n");
      out.write("							class=\"form-control\" id=\"gioiTinh\" name=\"gioiTinh\">\r\n");
      out.write("							<option></option>\r\n");
      out.write("							<option value=\"Nam\" ");
      out.print((gioiTinh.equals("Nam"))?"selected='selected'":"" );
      out.write(" >Nam</option>\r\n");
      out.write("							<option value=\"Nữ\" ");
      out.print((gioiTinh.equals("Nữ"))?"selected='selected'":"" );
      out.write(" >Nữ</option>\r\n");
      out.write("							<option value=\"Khác\" ");
      out.print((gioiTinh.equals("Khác"))?"selected='selected'":"" );
      out.write(" >Khác</option>\r\n");
      out.write("						</select>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"mb-3\">\r\n");
      out.write("						<label for=\"ngaySinh\" class=\"form-label\">Ngày sinh</label> <input\r\n");
      out.write("							type=\"date\" class=\"form-control\" id=\"ngaySinh\" name=\"ngaySinh\" value=\"");
      out.print(ngaySinh);
      out.write("\">\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-sm-6\">\r\n");
      out.write("					<h3>Địa chỉ</h3>\r\n");
      out.write("					<div class=\"mb-3\">\r\n");
      out.write("						<label for=\"diaChiKhachHang\" class=\"form-label\">Địa chỉ\r\n");
      out.write("							khách hàng</label> <input type=\"text\" class=\"form-control\"\r\n");
      out.write("							id=\"diaChiKhachHang\" name=\"diaChiKhachHang\" value=\"");
      out.print(diaChiKhachHang);
      out.write("\">\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"mb-3\">\r\n");
      out.write("						<label for=\"diaChiMuaHang\" class=\"form-label\">Địa chỉ mua\r\n");
      out.write("							hàng</label> <input type=\"text\" class=\"form-control\" id=\"diaChiMuaHang\"\r\n");
      out.write("							name=\"diaChiMuaHang\" value=\"");
      out.print(diaChiMuaHang);
      out.write("\">\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"mb-3\">\r\n");
      out.write("						<label for=\"diaChiNhanHang\" class=\"form-label\">Địa chỉ\r\n");
      out.write("							nhận hàng</label> <input type=\"text\" class=\"form-control\"\r\n");
      out.write("							id=\"diaChiNhanHang\" name=\"diaChiNhanHang\" value=\"");
      out.print(diaChiNhanHang);
      out.write("\">\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"mb-3\">\r\n");
      out.write("						<label for=\"dienThoai\" class=\"form-label\">Điện thoại</label> <input\r\n");
      out.write("							type=\"tel\" class=\"form-control\" id=\"dienThoai\" name=\"dienThoai\" value=\"");
      out.print(dienThoai);
      out.write("\">\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"mb-3\">\r\n");
      out.write("						<label for=\"email\" class=\"form-label\">Email</label> <input\r\n");
      out.write("							type=\"email\" class=\"form-control\" id=\"email\" name=\"email\"  value=\"");
      out.print(email);
      out.write("\">\r\n");
      out.write("					</div>\r\n");
      out.write("					<hr />					\r\n");
      out.write("					<div class=\"mb-3\">\r\n");
      out.write("						<label for=\"dongYNhanMail\" class=\"form-label\">Đồng ý nhận\r\n");
      out.write("							email</label> <input type=\"checkbox\" class=\"form-check-input\"\r\n");
      out.write("							id=\"dongYNhanMail\" name=\"dongYNhanMail\" ");
      out.print((dongYNhanMail?"checked":""));
      out.write(" >\r\n");
      out.write("					</div>\r\n");
      out.write("					<input class=\"btn btn-primary form-control\" type=\"submit\"\r\n");
      out.write("						value=\"Lưu thông tin\" name=\"submit\" id=\"submit\" />\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</form>\r\n");
      out.write("	</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	");
} 
      out.write('\r');
      out.write('\n');
      out.write('	');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../footer.jsp", out, false);
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
